spring:
  application:
    name: pang-server
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
jwt:
  access: 360000
  refresh: 30000000
  secret: ${JWT_KEY}